### ISSUE TITLE
Crash with Cave Generator Mod

### ISSUE THREAD

**Issue by WenXin20** [superfluke/WorleyCaves#1]
Forge v14.23.4.2745-1.12.2
Biomes O' Plenty v7.0.1.2399
Worley Caves v1.1.0
I got this crash while creating a world using the Biomes O' Plenty world type.
Here's the [crash report](https://gist.github.com/WenXin20/2966b22b15e9934d2146e1bf7093faa2).

**Comment by superfluke** [comment]
Actually an issue between Worley Caves + Cave Generator, though still pretty sure it's my fault. I'll take a look at it.

**Comment by WenXin20** [comment]
OK, thanks

**Comment by superfluke** [comment]
Fixed the crash reported, but the two mods are not still not totally compatible. From what I can tell, other crashes are going to have to handled on CaveGenerators end. 
For example, the two mods seem to work together if you blacklist Worley caves from dim 0 (so that Worley caves only appear in other dims, like Aroma's mining world). But if Worley's caves is not blacklisted from dim 0, CaveGenerators will crash.

**Comment by WenXin20** [comment]
Alright, thanks!
