### ISSUE TITLE
Worley doesn't play nice with WorldPainter

### ISSUE THREAD

**Issue by froggyfreaker** [superfluke/WorleyCaves#37]
Hi! I was hoping someone here can help me fix my problem? I've made a world in WorldPainter, but no matter what I do, WorldPainter maps just won't generate Worley caves. I assume that WorldPainter is taking over cave generation on these maps, since it has its own customizable cave gen. I'm also going to ask in the WorldPainter community, but maybe someone here will have answers. :)

**Comment by booleanbyte** [comment]
Hi, it's cool to hear you want to use Worley's Caves with a WP map, but sadly the cave generation for a WP map needs to be done by WP.

WP by necessity needs to do any cave generation during the world export. Cave generation happens at an early stage of chunk creation, and WP needs to have already taken care of it to output valid chunks that MC can/will read.

There is to my knowledge no way to get this interraction to work as desired, and neither can I see any reasonable changes we could make to acomodate the use case, and I'm rather sure that goes for WP as well.

**Comment by Captain-Chaos** [comment]
One possibility would be to create a WorldPainter plugin. I'd be willing to help with that.

**Comment by froggyfreaker** [comment]
> Hi, it's cool to hear you want to use Worley's Caves with a WP map, but sadly the cave generation for a WP map needs to be done by WP.
> 
> WP by necessity needs to do any cave generation during the world export. Cave generation happens at an early stage of chunk creation, and WP needs to have already taken care of it to output valid chunks that MC can/will read.
> 
> There is to my knowledge no way to get this interraction to work as desired, and neither can I see any reasonable changes we could make to acomodate the use case, and I'm rather sure that goes for WP as well.

Fiddlesticks! I figured something like this would be the problem. Thanks for the super quick reply though, I sure appreciate it.




> One possibility would be to create a WorldPainter plugin. I'd be willing to help with that.

I'm only a little familiar with WP plugins, but that sounds like the kind of thing that just might work. Any pointers/ideas?

**Comment by booleanbyte** [comment]
> One possibility would be to create a WorldPainter plugin. I'd be willing to help with that.

A plugin for it is a possibility of course. I'd be up for looking into that.

I've allready been sitting on the fence considering doing another more ambitious WP plugin for a little while, so this might actually serve as a nice and little project to get a little up and walking with making plugins.

**Comment by Captain-Chaos** [comment]
> A plugin for it is a possibility of course. I'd be up for looking into that.

The WorldPainter plugin mechanism is pretty primitive and immature, but I believe it's good enough (indeed I created it for) things like this. A plugin can provide its own layer, together with layer exporters that can modify the map as it is being exported, either early in the process when the chunks are being created (if it doesn't need access to other chunks) and/or later on an entire region.

**Comment by booleanbyte** [comment]
That sound much like what I gathered from my earlier experience of dabbling with WP for a few hours. Creating the implementation for a relativbely simple new layer was rather straight forwards (I didn't get into doing any configuration and UI stuff though, so I don't know any about that), my problems where mostly related to geting the development enviroment somewhat set up.

Since the original issue here is nothing that can be addressed by the mod, and a plugin would be more of a tangential project in relation to this mod, I think it would be appropriate to move further conversation on plugin making somewhere else (I'll send a PM on reddit to start with and we can figure out the rest from there), and let @superfluke close this issue. I'll add a comment here later, linking to a finished plugin when that's done.
